title: "RefereeIQ"
email: hello@refereeiq.app
description: "Rugby laws, explained in seconds."
url: "https://justinxhale.github.io"
baseurl: "/refereeiq-site"

remote_theme: jeromelachaud/freelancer-theme
plugins:
  - jekyll-remote-theme

# Navbar links
navbar-links:
  Home: /
  Privacy: /privacy.html
  Support: /support.html

# Branding
avatar: /assets/icon-512.png
favicon: /assets/icon-512.png

# Social (optional)
social-network-links:
  github: JustinXHale
  email: hello@refereeiq.app

markdown: kramdown
permalink: pretty
