title: RefereeIQ
description: Rugby laws, explained in seconds.
url: "https://justinxhale.github.io"
baseurl: "/refereeiq-site"   # keep this since it's a project page
logo: /assets/icon-512.png
favicon: /assets/icon-512.png

remote_theme: figs-xyz/jekyll-theme-figs   # ← paste the Figs theme identifier here
plugins:
  - jekyll-remote-theme

# Optional nav (many themes read this; harmless if ignored)
nav:
  - name: Home
    link: /
  - name: Privacy
    link: /privacy.html
  - name: Support
    link: /support.html
