# Jekyll config for a simple project site that renders Markdown with a custom layout
url: "https://justinxhale.github.io"
baseurl: "/refereeiq-site"

title: "RefereeIQ"
description: "Rugby laws, explained in seconds."

markdown: kramdown
permalink: pretty
